services:
  flyshadow-agent:
    image: ghcr.io/sebastian0619/flyshadow-agent:latest
    container_name: flyshadow-agent
    network_mode: host
    restart: unless-stopped
    environment:
      # Agent配置
      - AGENT_PASSWORD=${AGENT_PASSWORD:-12c5a79c-b3a5-11ef-a595-0016d7606fb8}
      - AGENT_NODE_ID=${AGENT_NODE_ID:-165}
    volumes:
      # 配置文件挂载
      - ./config.yaml:/app/config.yaml:ro 